		DROP TABLE IF EXISTS Vendor2Mensa;
	DROP TABLE IF EXISTS Order2Ingredient;
	DROP TABLE IF EXISTS Ingredient2Vendor;
	DROP TABLE IF EXISTS Meal2Menu;
	DROP TABLE IF EXISTS Meal2Ingredient;	
	DROP TABLE IF EXISTS Meal;
	DROP TABLE IF EXISTS Storage;
	DROP TABLE IF EXISTS Ingredient;
	DROP TABLE IF EXISTS Day;
	DROP TABLE IF EXISTS Served;
	DROP TABLE IF EXISTS Menu;
	DROP TABLE IF EXISTS Bill;
	DROP TABLE IF EXISTS Order;
	DROP TABLE IF EXISTS Vendor;
	DROP TABLE IF EXISTS Mensa;

	
	CREATE TABLE Ingredient (
		ID BIGINT UNSIGNED NOT NULL,
		
		name VARCHAR(255) NOT NULL,

		unit enum('kg','l'),

		price FLOAT NOT NULL,

		PRIMARY KEY (ID)

	)ENGINE=INNODB;	
	
	
	CREATE TABLE Meal (
		ID BIGINT UNSIGNED NOT NULL,
		
		name VARCHAR(255) NOT NULL,

		unit enum('main_dish','dessert','starter')

		PRIMARY KEY (ID)

	)ENGINE=INNODB;	
	
	CREATE TABLE Meal2Ingredient (

		ID_meal BIGINT UNSIGNED NOT NULL,

		ID_ingredient BIGINT UNSIGNED NOT NULL,
		
		FOREIGN KEY (ID_meal) REFERENCES Meal(ID)

		ON UPDATE CASCADE ON DELETE CASCADE,

		FOREIGN KEY (ID_ingredient) REFERENCES Ingredient(ID)

		ON UPDATE CASCADE ON DELETE CASCADE

	)ENGINE=INNODB;
	
	CREATE TABLE Day (
		date DATE NOT NULL,
		PRIMARY KEY (date)
	) ENGINE=INNODB ;
	
	CREATE TABLE Menu (
		ID BIGINT UNSIGNED NOT NULL,
		price FLOAT NOT NULL,
		name VARCHAR(255) NOT NULL,
		
		PRIMARY KEY (ID)
	) ENGINE=INNODB ;	
		
	CREATE TABLE Meal2Menu (
		type enum ('starter','main_dish','dessert'),
		ID_menu BIGINT UNSIGNED NOT NULL,
		ID_meal BIGINT UNSIGNED NOT NULL,
		
		FOREIGN KEY (ID_menu) REFERENCES Menu(ID)
		ON UPDATE CASCADE ON DELETE CASCADE,
		
		FOREIGN KEY (ID_meal) REFERENCES Meal(ID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	
	) ENGINE=INNODB;	
		
	CREATE TABLE Served (
		ID_menu BIGINT UNSIGNED NOT NULL,
		date DATE NOT NULL,
		
		FOREIGN KEY (ID_menu) REFERENCES Menu(ID)
		ON UPDATE CASCADE ON DELETE CASCADE,
		
		FOREIGN KEY (date) REFERENCES Date(date)
		ON UPDATE CASCADE ON DELETE CASCADE,
	
	) ENGINE=INNODB;		
		

	CREATE TABLE Vendor (
		ID BIGINT UNSIGNED NOT NULL,
		address  VARCHAR(255) NOT NULL, 
		
		PRIMARY KEY (ID)

	)ENGINE=INNODB ;
			
	CREATE TABLE Ingredient2Vendor (
		ID_vendor BIGINT UNSIGNED NOT NULL,
		ID_ingredient BIGINT UNSIGNED NOT NULL,
		FOREIGN KEY (ID_ingredient) REFERENCES Vendor(ID)
		ON UPDATE CASCADE ON DELETE CASCADE,
		
		FOREIGN KEY (ID_vendor) REFERENCES Menu(ID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	)ENGINE=INNODB ;
			
	CREATE TABLE Order (
	
		ID BIGINT UNSIGNED NOT NULL,
		vendor_ID BIGINT UNSIGNED NOT NULL,

		date_ordered DATE NOT NULL,

		date_delivered DATE NOT NULL,

		PRIMARY KEY (ID),
		
		FOREIGN KEY (vendor_ID) REFERENCES Vendor(ID)

		ON UPDATE CASCADE ON DELETE CASCADE
				
	)ENGINE=INNODB;	
		
		CREATE TABLE Mensa (
		ID BIGINT UNSIGNED NOT NULL,
		university_name VARCHAR(255) NOT NULL,
		
		PRIMARY KEY (ID)

	)ENGINE=INNODB;	
		
	CREATE TABLE Storage (
		ID_ingredient BIGINT UNSIGNED NOT NULL,

		quantity BIGINT,

		PRIMARY KEY (ID_ingredient)

	)ENGINE=INNODB;	
		
			CREATE TABLE Bill(
		
		ID_order BIGINT UNSIGNED NOT NULL,
		IBAN VARCHAR(40) NOT NULL,
		BIC VARCHAR(40) NOT NULL,
		total_sum FLOAT,

		FOREIGN KEY (ID_order) REFERENCES Order(ID)
		
		ON UPDATE CASCADE ON DELETE CASCADE

	)ENGINE=INNODB;
		
		
	CREATE TABLE Order2Ingredient (
		ID_order BIGINT UNSIGNED NOT NULL,
		ID_ingredient BIGINT UNSIGNED NOT NULL,
		quantity BIGINT UNSIGNED NOT NULL,
		prie FLOAT NOT NULL,

		FOREIGN KEY (ID_order) REFERENCES Order(ID)

		ON UPDATE CASCADE ON DELETE CASCADE,

		FOREIGN KEY (ID_ingredient) REFERENCES Ingredient(ID)

		ON UPDATE CASCADE ON DELETE CASCADE
	)ENGINE=INNODB;
	
	
	CREATE TABLE Vendor2Mensa (

		ID_mensa BIGINT UNSIGNED NOT NULL,

		ID_vendor BIGINT UNSIGNED NOT NULL,
		
		FOREIGN KEY (ID_mensa) REFERENCES Mensa(ID)

		ON UPDATE CASCADE ON DELETE CASCADE,

		FOREIGN KEY (ID_vendor) REFERENCES Vendor(ID)

		ON UPDATE CASCADE ON DELETE CASCADE

	)ENGINE=INNODB;
	
	




	



	
	
	

